add signing the right way

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -3,30 +3,34 @@ workflows:
     name: Codemagic test app android
     max_build_duration: 120
     instance_type: mac_mini_m1
-    # environment:
-    #   android_signing:
-    #     - keystore_reference
-    #   groups:
-    #     - google_play
-    #   vars:
-    #     PACKAGE_NAME: "io.codemagic.sample.androidnative"
+    environment:
+      android_signing:
+        - keystore_reference
+      groups:
+        - google_play
+      vars:
+        PACKAGE_NAME: "io.codemagic.sample.androidnative"
     scripts:
-      # - name: Set Android SDK location
-      #   script: |
-      #     LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
-      #     if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
-      #         # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
-      #         UPDATED_BUILD_NUMBER=$BUILD_NUMBER
-      #     else
-      #         UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
-      #     fi
-      #     ./gradlew bundleRelease -PversionCode=$UPDATED_BUILD_NUMBER -PversionName=1.0.$UPDATED_BUILD_NUMBER
+      - name: Set Android SDK location
+        script: |
+          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
+              # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
+              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+          else
+              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+          fi
+          ./gradlew bundleRelease -PversionCode=$UPDATED_BUILD_NUMBER -PversionName=1.0.$UPDATED_BUILD_NUMBER
       - name: Unit tests
         script: |
           mkdir -p test-results
           flutter test --machine > test-results/flutter.json
         test_report: test-results/flutter.json
+      - name: Build Android APK
+        working_directory: android
+        script: ./gradlew assembleRelease
     artifacts:
+      - app/build/outputs/**/**/*.apk
       - app/build/outputs/**/*.aab
     publishing:
       email:
